language: node_js
node_js: node
addons:
  firefox: latest
script: npm run ci
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: >-
      I+oNEP2jfHBxU8FQ4k45YtJrLLrQqPiekV5NxoMEAgj5uelulVVipWz5qG+h/eXnscOkt0OUrsHf6T5IC4uKrd9RwM5R5txavNETFElTHaBjqJJpQiv8quTUrOjsnSQqFnjG7BL/gxWeMVSmUSXThLxCov6QFIjJSTb1Jk26q108gbCNk8kjP667RejUkFeqCXzsFmf8JTSwzmHo7M6ZuRH1/HRl4/Gx9yZCeMAzWvyTysKHqigJbLGmNBZRmbMJQJTvkqeO6J5RGjZ7TBhJ2IT9I2F9YMrjEUAN/71MgUk8ftgDs5GJpSECJIqu5cjeASXgNmlMQ6801UNiYq5X1yJOOxCw5VDwSctrOjUSQOpGnfzetjS6viDAjAbqHTNBdzQuyeLec0iXCB7GGE9qVrxlmhCm/g6bESokWIsMCj+Zz3IgpjUqP/8nHscEWkCk2I5YVsDN5TzEQL4SP1+Fi78f4tWMjwPCC8do2ZcVSB83ez69GDQh/r6Hax0KrGa+1aNdu4DP9BvFp4/cnEBwLuMMVNe0i5zGziSAxHslzo9VQc64kcYmOlAaTu82gSM+cC5+nznbh+8oihUjNLtaTlharTBOFFxs/7v35CW29YP82GzvzuiOqAqWNiZoa1EVmXurNNfcr2ToCEUKD894LqU5ItsTvzFO2jw4mwJRXFE=
  'on':
    tags: true
    repo: canjs/can-observable-bindings
  skip_cleanup: true
dist: xenial
services:
  - xvfb
